import type { Metadata } from "next";
import "../styles/globals.css";
import Navbar from "../components/layout/Navbar";
import Footer from "../components/layout/Footer";
import { UserTypeProvider } from "@/context/UserTypeContext";

export const metadata: Metadata = {
  title: "Invoice Ease",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <UserTypeProvider>
          <Navbar />
          {children}
          <Footer />
        </UserTypeProvider>
      </body>
    </html>
  );
}


